from fastapi import APIRouter, Query

router = APIRouter(prefix="/events", tags=["events"])


@router.get("", summary="Query derived race events")
async def list_events(
    type: str | None = Query(None, description="e.g. race_call, jump_imminent, result_announced"),
    feed_id: int | None = Query(None),
    race_class: str | None = Query(None),
    since: str | None = Query(None, description="ISO 8601 timestamp"),
    limit: int = Query(50, le=200),
):
    """
    Query derived race events across all races. Events are generated by the
    intelligence pipeline from audio + OCR + timeline signals.
    """
    return {"events": [], "limit": limit}
